import Head from "next/head";
import SinovJoyi from "@/SinovJoyi";
import {useGetEducation} from "@/hooks/EducationQuery";
import {useGetByEduCentreReview, useGetByIdReview, useGetReview, usePostReview} from "@/hooks/ReviewQuery";
import {useGetByIdSubjects} from "@/hooks/SubjectsQuery";
import {PostReviewI} from "@/interface";


export default function Home() {
    const {mutate}=usePostReview()

    const postReview=():void=>{
        const data1:PostReviewI={
            user: '',
            rating: 5,
            reviewText: 'Yaxshi o\'quv markazi'
        }
        const data=JSON.stringify(data1)
        mutate({url:'preview',id:"63fcff38851ca3a4544e7af2",data})
    }

    return (
        <>
        <button onClick={postReview}>Send Review</button>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SinovJoyi/>
        </>
    );
}
