import Head from "next/head";
import SinovJoyi from "@/SinovJoyi";
import {useGetEducation} from "@/hooks/EducationQuery";
import {useGetByEduCentreReview, useGetByIdReview, useGetReview} from "@/hooks/ReviewQuery";


export default function Home() {
    const {data,error,isLoading}=useGetByEduCentreReview('63fd0ac101554397ebb75a51')
    console.log(isLoading)
    console.log(data)
    return (
        <>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SinovJoyi/>
        </>
    );
}
